.DEFAULT_GOAL := help
SHELL := /bin/bash

UV ?= uv
COMPOSE_FILE := deploy/compose/docker-compose.yml
COMPOSE_OBS_FILE := deploy/compose/docker-compose.obs.yml
# The signing key of auth in the local stack: a file standing in for the
# Kubernetes Secret. Generated by "make keys", ignored by git.
SIGNING_KEY := deploy/compose/secrets/auth-signing-key.pem
COMPOSE := docker compose -f $(COMPOSE_FILE)
COMPOSE_WITH_OBS := docker compose -f $(COMPOSE_FILE) -f $(COMPOSE_OBS_FILE)
OBS_CONTAINERS := prometheus grafana tempo loki alloy

.PHONY: help sync hooks check lint format type test test-unit keys up obs-up obs-down down logs migrate seed kind-up kind-down clean

help: ## Show available commands
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-12s\033[0m %s\n", $$1, $$2}'

sync: ## Create or update the virtual environment from the lock file
	$(UV) sync --all-packages

hooks: ## Install the git hooks of pre-commit
	$(UV) run pre-commit install

check: ## Run every pre-commit hook over the whole repository
	$(UV) run pre-commit run --all-files

lint: ## Static style checks
	$(UV) run ruff check .
	$(UV) run ruff format --check .

format: ## Rewrite files to the project style
	$(UV) run ruff check --fix .
	$(UV) run ruff format .

type: ## Static type checks
	$(UV) run mypy .
	@# mypy refuses to see two files with the same module name in one run, and
	@# every service has a tests/test_smoke.py. They are checked one at a time.
	@for tests in services/*/tests; do \
		echo "==> $$tests"; \
		$(UV) run mypy --config-file=mypy.tests.toml "$$tests"; \
	done

test: ## Run the whole test suite
	@$(UV) run pytest; status=$$?; test $$status -eq 0 -o $$status -eq 5

test-unit: ## Run only the tests that need no Docker
	@$(UV) run pytest -m "not integration"; status=$$?; test $$status -eq 0 -o $$status -eq 5

keys: $(SIGNING_KEY) ## Generate the local RS256 signing key of auth, if absent

# Never regenerated over an existing file: the kid is derived from the key, so
# replacing it would strand every token already issued against the local stack.
#
# 0644 rather than the 0600 the script defaults to. The file is bind-mounted
# into the auth container, which runs as uid 10001, while this writes it as the
# developer's own user -- a 0600 key is one the service cannot read, and it
# fails at startup with a PermissionError. The key here is local, throwaway and
# ignored by git; a deployed one keeps 0600 and arrives as a Kubernetes Secret
# rather than from this rule.
$(SIGNING_KEY):
	$(UV) run python scripts/gen_keys.py --out $(SIGNING_KEY) --mode 644

up: keys ## Start the local environment
	@test -f $(COMPOSE_FILE) || { echo "$(COMPOSE_FILE) not found"; exit 1; }
	$(COMPOSE) up -d --build

obs-up: keys ## Start the local environment with Prometheus, Grafana, Tempo, Loki and Alloy
	@test -f $(COMPOSE_FILE) || { echo "$(COMPOSE_FILE) not found"; exit 1; }
	$(COMPOSE_WITH_OBS) up -d --build
	@echo "Grafana: http://localhost:3000  Prometheus: http://localhost:9090"

# The services are brought up again from the main file alone: that recreates
# them with tracing off, instead of leaving them exporting to a Tempo that is gone.
obs-down: ## Stop the observability profile, keep the local environment running
	$(COMPOSE_WITH_OBS) rm --stop --force $(OBS_CONTAINERS)
	$(COMPOSE) up -d

down: ## Stop the local environment
	@test -f $(COMPOSE_FILE) || { echo "$(COMPOSE_FILE) not found"; exit 1; }
	@# The containers of the observability profile belong to the same project,
	@# and without --remove-orphans they would outlive the stack.
	$(COMPOSE) down -v --remove-orphans

logs: ## Follow the local environment logs
	@test -f $(COMPOSE_FILE) || { echo "$(COMPOSE_FILE) not found"; exit 1; }
	$(COMPOSE) logs -f

migrate: ## Apply database migrations of every service
	@test -x scripts/migrate.sh || { echo "scripts/migrate.sh not found"; exit 1; }
	./scripts/migrate.sh

seed: ## Load demo data into the local environment
	@test -x scripts/seed.sh || { echo "scripts/seed.sh not found"; exit 1; }
	./scripts/seed.sh

kind-up: ## Create the kind cluster and install the Helm releases
	@test -x scripts/kind-up.sh || { echo "scripts/kind-up.sh not found"; exit 1; }
	./scripts/kind-up.sh

kind-down: ## Delete the kind cluster
	@test -x scripts/kind-down.sh || { echo "scripts/kind-down.sh not found"; exit 1; }
	./scripts/kind-down.sh

clean: ## Remove build and test artefacts
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	rm -rf .pytest_cache .mypy_cache .ruff_cache .coverage htmlcov
