"""The Alembic environment every service shares.

A service ``migrations/env.py`` is three lines::

    from barber_common.db.alembic_env import run_migrations
    from barber_booking.models import metadata

    run_migrations(target_metadata=metadata)

Everything that is easy to get subtly wrong lives here instead of being copied
five times: the async engine, ``compare_type`` (without it a column changing
from ``varchar(64)`` to ``varchar(128)`` is autogenerated as nothing at all),
and the DSN coming from the environment rather than from ``alembic.ini`` --
the file is in git, and the password is not.
"""

from __future__ import annotations

import asyncio

from alembic import context
from sqlalchemy import Connection, MetaData
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.pool import NullPool

from barber_common.db.migrations import MigrationSettings

__all__ = ["run_migrations"]


def run_migrations(*, target_metadata: MetaData | None = None, dsn: str | None = None) -> None:
    """Run the migrations the way Alembic was invoked, offline or online.

    ``dsn`` overrides the environment; the tests use it, the migration Job does
    not need it.
    """
    url = dsn or _resolve_dsn()
    if context.is_offline_mode():
        _run_offline(url, target_metadata)
        return
    asyncio.run(_run_online(url, target_metadata))


def _resolve_dsn() -> str:
    """Take the DSN from ``alembic.ini`` if it is there, otherwise from env."""
    configured = context.config.get_main_option("sqlalchemy.url")
    if configured:
        return configured
    return MigrationSettings().dsn


def _run_offline(url: str, target_metadata: MetaData | None) -> None:
    """Emit SQL to stdout instead of executing it.

    Used to review what a migration will do to a database nobody wants to
    experiment on.
    """
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


async def _run_online(url: str, target_metadata: MetaData | None) -> None:
    """Apply the migrations against the database.

    ``NullPool``: a migration run is one connection for a few seconds, and a
    pooled connection left open keeps a lock on the schema after the Job has
    finished.
    """
    engine = async_engine_from_config(
        {"sqlalchemy.url": url},
        prefix="sqlalchemy.",
        poolclass=NullPool,
    )
    try:
        async with engine.connect() as connection:
            await connection.run_sync(_apply, target_metadata)
    finally:
        await engine.dispose()


def _apply(connection: Connection, target_metadata: MetaData | None) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Without it a changed column type is silently not autogenerated.
        compare_type=True,
        compare_server_default=True,
    )
    with context.begin_transaction():
        context.run_migrations()
