"""ORM models of the notification service.

Importing the shared models is what puts ``outbox`` and ``processed_events``
into the metadata Alembic compares the database against. Without the import an
autogenerated revision would cheerfully propose to drop both tables. The models
of this service are listed for the same reason.
"""

from barber_common.db.base import Base, metadata
from barber_common.kafka.dedup import ProcessedEvent
from barber_common.outbox.models import OutboxMessage
from barber_notification.models.notification import Notification
from barber_notification.models.recipient import Recipient
from barber_notification.models.telegram_link_code import TelegramLinkCode

__all__ = [
    "Base",
    "Notification",
    "OutboxMessage",
    "ProcessedEvent",
    "Recipient",
    "TelegramLinkCode",
    "metadata",
]
