"""ORM models of the notification service.

Importing the shared models is what puts ``outbox`` and ``processed_events``
into the metadata Alembic compares the database against. Without the import an
autogenerated revision would cheerfully propose to drop both tables.
"""

from barber_common.db.base import Base, metadata
from barber_common.kafka.dedup import ProcessedEvent
from barber_common.outbox.models import OutboxMessage

__all__ = ["Base", "OutboxMessage", "ProcessedEvent", "metadata"]
