"""ORM models of the booking service.

Importing the shared models is what puts ``outbox`` and ``processed_events``
into the metadata Alembic compares the database against. Without the import an
autogenerated revision would cheerfully propose to drop both tables. The models
of this service are listed for the same reason.
"""

from barber_booking.models.booking import Booking
from barber_booking.models.master_settings import MasterSettings
from barber_booking.models.schedule_exception import ScheduleException
from barber_booking.models.schedule_template import ScheduleTemplate
from barber_common.db.base import Base, metadata
from barber_common.kafka.dedup import ProcessedEvent
from barber_common.outbox.models import OutboxMessage

__all__ = [
    "Base",
    "Booking",
    "MasterSettings",
    "OutboxMessage",
    "ProcessedEvent",
    "ScheduleException",
    "ScheduleTemplate",
    "metadata",
]
